apiVersion: apps/v1
kind: Deployment
metadata:
  name: msemail-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msemail
  template:
    metadata:
      labels:
        app: msemail
    spec:
      containers:
        - name: msemail
          image: marimber/msemail:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: configmap
---
apiVersion: v1
kind: Service
metadata:
  name: msemail-service
spec:
  selector:
    app: msemail
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30003
      targetPort: 3000
  type: NodePort